//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace LWSupportUtilityWeb.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LWSupportUtility : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LWSupportUtility object using the connection string found in the 'LWSupportUtility' section of the application configuration file.
        /// </summary>
        public LWSupportUtility() : base("name=LWSupportUtility", "LWSupportUtility")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LWSupportUtility object.
        /// </summary>
        public LWSupportUtility(string connectionString) : base(connectionString, "LWSupportUtility")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LWSupportUtility object.
        /// </summary>
        public LWSupportUtility(EntityConnection connection) : base(connection, "LWSupportUtility")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblLookupCategory> tblLookupCategories
        {
            get
            {
                if ((_tblLookupCategories == null))
                {
                    _tblLookupCategories = base.CreateObjectSet<tblLookupCategory>("tblLookupCategories");
                }
                return _tblLookupCategories;
            }
        }
        private ObjectSet<tblLookupCategory> _tblLookupCategories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblLookupItem> tblLookupItems
        {
            get
            {
                if ((_tblLookupItems == null))
                {
                    _tblLookupItems = base.CreateObjectSet<tblLookupItem>("tblLookupItems");
                }
                return _tblLookupItems;
            }
        }
        private ObjectSet<tblLookupItem> _tblLookupItems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblSecretQuestion> tblSecretQuestions
        {
            get
            {
                if ((_tblSecretQuestions == null))
                {
                    _tblSecretQuestions = base.CreateObjectSet<tblSecretQuestion>("tblSecretQuestions");
                }
                return _tblSecretQuestions;
            }
        }
        private ObjectSet<tblSecretQuestion> _tblSecretQuestions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblUser> tblUsers
        {
            get
            {
                if ((_tblUsers == null))
                {
                    _tblUsers = base.CreateObjectSet<tblUser>("tblUsers");
                }
                return _tblUsers;
            }
        }
        private ObjectSet<tblUser> _tblUsers;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblLookupCategories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblLookupCategories(tblLookupCategory tblLookupCategory)
        {
            base.AddObject("tblLookupCategories", tblLookupCategory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblLookupItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblLookupItems(tblLookupItem tblLookupItem)
        {
            base.AddObject("tblLookupItems", tblLookupItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblSecretQuestions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblSecretQuestions(tblSecretQuestion tblSecretQuestion)
        {
            base.AddObject("tblSecretQuestions", tblSecretQuestion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblUsers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblUsers(tblUser tblUser)
        {
            base.AddObject("tblUsers", tblUser);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LWSupportUtility.Models", Name="tblLookupCategory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblLookupCategory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblLookupCategory object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="iCategoryID">Initial value of the iCategoryID property.</param>
        /// <param name="cCategoryName">Initial value of the cCategoryName property.</param>
        public static tblLookupCategory CreatetblLookupCategory(global::System.Int32 id, global::System.Int32 iCategoryID, global::System.String cCategoryName)
        {
            tblLookupCategory tblLookupCategory = new tblLookupCategory();
            tblLookupCategory.ID = id;
            tblLookupCategory.iCategoryID = iCategoryID;
            tblLookupCategory.cCategoryName = cCategoryName;
            return tblLookupCategory;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 iCategoryID
        {
            get
            {
                return _iCategoryID;
            }
            set
            {
                OniCategoryIDChanging(value);
                ReportPropertyChanging("iCategoryID");
                _iCategoryID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("iCategoryID");
                OniCategoryIDChanged();
            }
        }
        private global::System.Int32 _iCategoryID;
        partial void OniCategoryIDChanging(global::System.Int32 value);
        partial void OniCategoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cCategoryName
        {
            get
            {
                return _cCategoryName;
            }
            set
            {
                OncCategoryNameChanging(value);
                ReportPropertyChanging("cCategoryName");
                _cCategoryName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cCategoryName");
                OncCategoryNameChanged();
            }
        }
        private global::System.String _cCategoryName;
        partial void OncCategoryNameChanging(global::System.String value);
        partial void OncCategoryNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LWSupportUtility.Models", Name="tblLookupItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblLookupItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblLookupItem object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="iLookupitemID">Initial value of the iLookupitemID property.</param>
        /// <param name="cLookupItemname">Initial value of the cLookupItemname property.</param>
        /// <param name="iLookupCatID">Initial value of the iLookupCatID property.</param>
        /// <param name="dTimestamp">Initial value of the dTimestamp property.</param>
        public static tblLookupItem CreatetblLookupItem(global::System.Int32 id, global::System.Int32 iLookupitemID, global::System.String cLookupItemname, global::System.Int32 iLookupCatID, global::System.DateTime dTimestamp)
        {
            tblLookupItem tblLookupItem = new tblLookupItem();
            tblLookupItem.ID = id;
            tblLookupItem.iLookupitemID = iLookupitemID;
            tblLookupItem.cLookupItemname = cLookupItemname;
            tblLookupItem.iLookupCatID = iLookupCatID;
            tblLookupItem.dTimestamp = dTimestamp;
            return tblLookupItem;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 iLookupitemID
        {
            get
            {
                return _iLookupitemID;
            }
            set
            {
                OniLookupitemIDChanging(value);
                ReportPropertyChanging("iLookupitemID");
                _iLookupitemID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("iLookupitemID");
                OniLookupitemIDChanged();
            }
        }
        private global::System.Int32 _iLookupitemID;
        partial void OniLookupitemIDChanging(global::System.Int32 value);
        partial void OniLookupitemIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cLookupItemname
        {
            get
            {
                return _cLookupItemname;
            }
            set
            {
                OncLookupItemnameChanging(value);
                ReportPropertyChanging("cLookupItemname");
                _cLookupItemname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cLookupItemname");
                OncLookupItemnameChanged();
            }
        }
        private global::System.String _cLookupItemname;
        partial void OncLookupItemnameChanging(global::System.String value);
        partial void OncLookupItemnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 iLookupCatID
        {
            get
            {
                return _iLookupCatID;
            }
            set
            {
                OniLookupCatIDChanging(value);
                ReportPropertyChanging("iLookupCatID");
                _iLookupCatID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("iLookupCatID");
                OniLookupCatIDChanged();
            }
        }
        private global::System.Int32 _iLookupCatID;
        partial void OniLookupCatIDChanging(global::System.Int32 value);
        partial void OniLookupCatIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dTimestamp
        {
            get
            {
                return _dTimestamp;
            }
            set
            {
                OndTimestampChanging(value);
                ReportPropertyChanging("dTimestamp");
                _dTimestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dTimestamp");
                OndTimestampChanged();
            }
        }
        private global::System.DateTime _dTimestamp;
        partial void OndTimestampChanging(global::System.DateTime value);
        partial void OndTimestampChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LWSupportUtility.Models", Name="tblSecretQuestion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblSecretQuestion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblSecretQuestion object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="iSecretQuestionID">Initial value of the iSecretQuestionID property.</param>
        /// <param name="iLookupCatID">Initial value of the iLookupCatID property.</param>
        /// <param name="iLookupItemID">Initial value of the iLookupItemID property.</param>
        /// <param name="dTimestamp">Initial value of the dTimestamp property.</param>
        public static tblSecretQuestion CreatetblSecretQuestion(global::System.Int32 id, global::System.Int32 iSecretQuestionID, global::System.Int32 iLookupCatID, global::System.Int32 iLookupItemID, global::System.DateTime dTimestamp)
        {
            tblSecretQuestion tblSecretQuestion = new tblSecretQuestion();
            tblSecretQuestion.ID = id;
            tblSecretQuestion.iSecretQuestionID = iSecretQuestionID;
            tblSecretQuestion.iLookupCatID = iLookupCatID;
            tblSecretQuestion.iLookupItemID = iLookupItemID;
            tblSecretQuestion.dTimestamp = dTimestamp;
            return tblSecretQuestion;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 iSecretQuestionID
        {
            get
            {
                return _iSecretQuestionID;
            }
            set
            {
                OniSecretQuestionIDChanging(value);
                ReportPropertyChanging("iSecretQuestionID");
                _iSecretQuestionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("iSecretQuestionID");
                OniSecretQuestionIDChanged();
            }
        }
        private global::System.Int32 _iSecretQuestionID;
        partial void OniSecretQuestionIDChanging(global::System.Int32 value);
        partial void OniSecretQuestionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 iLookupCatID
        {
            get
            {
                return _iLookupCatID;
            }
            set
            {
                OniLookupCatIDChanging(value);
                ReportPropertyChanging("iLookupCatID");
                _iLookupCatID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("iLookupCatID");
                OniLookupCatIDChanged();
            }
        }
        private global::System.Int32 _iLookupCatID;
        partial void OniLookupCatIDChanging(global::System.Int32 value);
        partial void OniLookupCatIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 iLookupItemID
        {
            get
            {
                return _iLookupItemID;
            }
            set
            {
                OniLookupItemIDChanging(value);
                ReportPropertyChanging("iLookupItemID");
                _iLookupItemID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("iLookupItemID");
                OniLookupItemIDChanged();
            }
        }
        private global::System.Int32 _iLookupItemID;
        partial void OniLookupItemIDChanging(global::System.Int32 value);
        partial void OniLookupItemIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dTimestamp
        {
            get
            {
                return _dTimestamp;
            }
            set
            {
                OndTimestampChanging(value);
                ReportPropertyChanging("dTimestamp");
                _dTimestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dTimestamp");
                OndTimestampChanged();
            }
        }
        private global::System.DateTime _dTimestamp;
        partial void OndTimestampChanging(global::System.DateTime value);
        partial void OndTimestampChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LWSupportUtility.Models", Name="tblUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblUser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblUser object.
        /// </summary>
        /// <param name="iUserID">Initial value of the iUserID property.</param>
        /// <param name="cUsername">Initial value of the cUsername property.</param>
        /// <param name="cPassword">Initial value of the cPassword property.</param>
        /// <param name="cFirstname">Initial value of the cFirstname property.</param>
        /// <param name="cLastname">Initial value of the cLastname property.</param>
        /// <param name="cEmail">Initial value of the cEmail property.</param>
        /// <param name="iSecretQuestionID">Initial value of the iSecretQuestionID property.</param>
        /// <param name="cSecretAnswer">Initial value of the cSecretAnswer property.</param>
        /// <param name="dTimestamp">Initial value of the dTimestamp property.</param>
        public static tblUser CreatetblUser(global::System.Int32 iUserID, global::System.String cUsername, global::System.String cPassword, global::System.String cFirstname, global::System.String cLastname, global::System.String cEmail, global::System.Int32 iSecretQuestionID, global::System.String cSecretAnswer, global::System.DateTime dTimestamp)
        {
            tblUser tblUser = new tblUser();
            tblUser.iUserID = iUserID;
            tblUser.cUsername = cUsername;
            tblUser.cPassword = cPassword;
            tblUser.cFirstname = cFirstname;
            tblUser.cLastname = cLastname;
            tblUser.cEmail = cEmail;
            tblUser.iSecretQuestionID = iSecretQuestionID;
            tblUser.cSecretAnswer = cSecretAnswer;
            tblUser.dTimestamp = dTimestamp;
            return tblUser;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 iUserID
        {
            get
            {
                return _iUserID;
            }
            set
            {
                if (_iUserID != value)
                {
                    OniUserIDChanging(value);
                    ReportPropertyChanging("iUserID");
                    _iUserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("iUserID");
                    OniUserIDChanged();
                }
            }
        }
        private global::System.Int32 _iUserID;
        partial void OniUserIDChanging(global::System.Int32 value);
        partial void OniUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cUsername
        {
            get
            {
                return _cUsername;
            }
            set
            {
                OncUsernameChanging(value);
                ReportPropertyChanging("cUsername");
                _cUsername = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cUsername");
                OncUsernameChanged();
            }
        }
        private global::System.String _cUsername;
        partial void OncUsernameChanging(global::System.String value);
        partial void OncUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cPassword
        {
            get
            {
                return _cPassword;
            }
            set
            {
                OncPasswordChanging(value);
                ReportPropertyChanging("cPassword");
                _cPassword = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cPassword");
                OncPasswordChanged();
            }
        }
        private global::System.String _cPassword;
        partial void OncPasswordChanging(global::System.String value);
        partial void OncPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cFirstname
        {
            get
            {
                return _cFirstname;
            }
            set
            {
                OncFirstnameChanging(value);
                ReportPropertyChanging("cFirstname");
                _cFirstname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cFirstname");
                OncFirstnameChanged();
            }
        }
        private global::System.String _cFirstname;
        partial void OncFirstnameChanging(global::System.String value);
        partial void OncFirstnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cLastname
        {
            get
            {
                return _cLastname;
            }
            set
            {
                OncLastnameChanging(value);
                ReportPropertyChanging("cLastname");
                _cLastname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cLastname");
                OncLastnameChanged();
            }
        }
        private global::System.String _cLastname;
        partial void OncLastnameChanging(global::System.String value);
        partial void OncLastnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cEmail
        {
            get
            {
                return _cEmail;
            }
            set
            {
                OncEmailChanging(value);
                ReportPropertyChanging("cEmail");
                _cEmail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cEmail");
                OncEmailChanged();
            }
        }
        private global::System.String _cEmail;
        partial void OncEmailChanging(global::System.String value);
        partial void OncEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cMobileno
        {
            get
            {
                return _cMobileno;
            }
            set
            {
                OncMobilenoChanging(value);
                ReportPropertyChanging("cMobileno");
                _cMobileno = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cMobileno");
                OncMobilenoChanged();
            }
        }
        private global::System.String _cMobileno;
        partial void OncMobilenoChanging(global::System.String value);
        partial void OncMobilenoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cPhone
        {
            get
            {
                return _cPhone;
            }
            set
            {
                OncPhoneChanging(value);
                ReportPropertyChanging("cPhone");
                _cPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cPhone");
                OncPhoneChanged();
            }
        }
        private global::System.String _cPhone;
        partial void OncPhoneChanging(global::System.String value);
        partial void OncPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 iSecretQuestionID
        {
            get
            {
                return _iSecretQuestionID;
            }
            set
            {
                OniSecretQuestionIDChanging(value);
                ReportPropertyChanging("iSecretQuestionID");
                _iSecretQuestionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("iSecretQuestionID");
                OniSecretQuestionIDChanged();
            }
        }
        private global::System.Int32 _iSecretQuestionID;
        partial void OniSecretQuestionIDChanging(global::System.Int32 value);
        partial void OniSecretQuestionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cSecretAnswer
        {
            get
            {
                return _cSecretAnswer;
            }
            set
            {
                OncSecretAnswerChanging(value);
                ReportPropertyChanging("cSecretAnswer");
                _cSecretAnswer = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cSecretAnswer");
                OncSecretAnswerChanged();
            }
        }
        private global::System.String _cSecretAnswer;
        partial void OncSecretAnswerChanging(global::System.String value);
        partial void OncSecretAnswerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dTimestamp
        {
            get
            {
                return _dTimestamp;
            }
            set
            {
                OndTimestampChanging(value);
                ReportPropertyChanging("dTimestamp");
                _dTimestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dTimestamp");
                OndTimestampChanged();
            }
        }
        private global::System.DateTime _dTimestamp;
        partial void OndTimestampChanging(global::System.DateTime value);
        partial void OndTimestampChanged();

        #endregion

    
    }

    #endregion

    
}
